Bạn cho mình code full siêu đỉnh không thay đổi cấu trúc chỉ làm cho hay hơn mượt hơn và có khả năng add đề word, pdf lên hiệu quả hiện công thức toán học siêu đẹp như mơ mỗi câu có nút xóa và nút ctrl V, mọi thao tác đều có nút xóa và lưu lại vĩnh viễn nhé, rà soát mọi lỗi sai hiện tại!cho mình xin các nội dung bạn nâng cấp, và đề xuất nâng cấp để nâng cao hiệu quả!cuối cùng mỗi phần đều có code full, đổi tất cả firebase sang supabase, cuối cùng là các file code full cần chỉnh copy dán thôi tổng hợp từng file nếu file nào ảnh hưởng để chúng thống nhất thành 1 mối trong trang lms, bạn yêu cầu mình gửi từng file nhé, sao cho trang lms hoạt động hiệu quả, đây là cấu trúc bạn cần tuân thủ 
- Components
	+ components/AiAssistant.tsx
	+ components/AiExamGenerator.tsx
	+ components/AiTutor.tsx
+ components/ClassManagement.tsx
	+ components/CourseCard.tsx
	+ components/CourseViewer.tsx
+ components/ExamCard.tsx
	+ components/ExamDashboard.tsx
	+ components/ExamEditor.tsx
+ components/GameManagement.tsx
	+ components/GradeManagement.tsx
	+ components/Header.tsx
+ components/ImportExamFromFile.tsx
	+ components/Layout.tsx
	+ components/LoginScreen.tsx
+ components/MathPreview.tsx
	+ components/Sidebar.tsx
	+ components/StudentQuiz.tsx
+ components/Table.tsx
	+ components/Toast.tsx
- data
	+ data/mockData.ts
- pages
+ pages/AdminDashboard.tsx
	+ pages/ComponentGallery.tsx
+ pages/Dashboard.tsx
	+ pages/StudentDashboard.tsx
	+ pages/TeacherPortal.tsx
- services
	+ services/authService.ts
	+ services/dataServices.ts
	+ services/exam.service.ts
	+ services/geminiService.ts
	+ services/quizService.ts
	+ services/syncService.ts
- Types
	+ types/examFormat.ts
	+ types/supabaseClient.ts
- .gitignore
- App.tsx
- README.md
- constants.ts
- examFo
- index.css
- index.html
- index.tsx
- main.tsx
- metadata.json
- package.json
- supabase.ts
- tailwind.config.js
- tsconfig.json
- types.ts
- vercel.json
- vite.config.ts
Đây là  link google driver bạn có thể lưu trữ dữ liệu cùng supabase: https://drive.google.com/drive/folders/1Fw7Y7Z4vUDK0OsCiqetFoC-9dm6khv1B, bảng đăng nhập phải có giáo viên đăng nhập tên đăng nhập: huynhvannhan@gmail.com, mật khẩu huynhvannhan2020, tên hiển thị Thầy Huỳnh Văn Nhẫn, học sinh đăng nhập, và học sinh đăng ký cho giáo viên duyệt vào lớp cuối cùng phải cho mình file code full sạch từng file nhé, khắc phục lỗi đăng nhập
